### ISSUE TITLE
Change the promotions in ranges causes package tests to fail.

### ISSUE THREAD

**Issue by KristofferC** [jw3126/RangeHelpers.jl#2]
After https://github.com/JuliaLang/julia/pull/43059 there is a change in the result of `range` when it comes to mixed input types:

```jl
julia> start, step, length = (2.0, -1, 5)
(2.0, -1, 5)

julia> Base.range(start; step, length) |> typeof # 1.8
StepRangeLen{Float64, Float64, Int64, Int64}

julia> Base.range(start; step, length) |> typeof # 1.7
StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}
```

This causes some tests in this package (that check `===` ) to fail, see the PkgEval report https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/fb69baf_vs_40279f9/RangeHelpers.primary.log.

**Comment by jw3126** [comment]
Thanks for reporting!

**Comment by KristofferC** [comment]
This might be an issue on Julia's side though it seems.

**Comment by jw3126** [comment]
Ok, I think I will wait until 1.8 comes out and then fix any remaining test fails.

**Comment by KristofferC** [comment]
I think should be fixed by https://github.com/JuliaLang/julia/pull/44528

**Comment by KristofferC** [comment]
Indeed, fixed.
