### ISSUE TITLE
Support predicates like < <= >= >

### ISSUE THREAD

**Issue by aplavin** [jw3126/RangeHelpers.jl#4]
Everyone already knows these operators, so there would be:
- no need to learn new names like `strictbelow`,
- no need for `using RangeHelpers`, only `using RangeHelpers: range`,
- no ambiguity whether `below` is strict or not.

Potential examples: `range(start=10, stop=121.7, step=≤(25))`, `range(start = 0.0, stop = <(2.0), step = 1.0)`.

**Comment by jw3126** [comment]
This is a great suggestion. Should we add an alias for `around`, too? `≈` comes to mind, the only thing I dislike about it is, that one might expect certain tolerances from it.

**Comment by longemen3000** [comment]
you can dispatch directly on `>`, `<`, `≤` and `≥`:
```
julia> ≥(3)
(::Base.Fix2{typeof(>=), Int64}) (generic function with 1 method)
```

**Comment by aplavin** [comment]
Yeah, not sure about `≈`. For one, it's not `Base.Fix2`:
```
julia> >(1)
(::Base.Fix2{typeof(>), Int64}) (generic function with 1 method)

julia> ≈(1)
#787 (generic function with 1 method)
```
And yeah, Base doesn't support kwargs in `Fix2` anyway, `≈` would be pretty useless without them.

Other reasonable predicates: `∈(1:5)` (range), `∈(1..5)` and `∈(1 ± 0.5)` (IntervalSets`).

**Comment by jw3126** [comment]
Ok so probably we are stuck with `around`, but would be nice to have these aliases for the others.
Around does not care at all about tolerances, it just chooses the closest compatible endpoint/step.

**Comment by jw3126** [comment]
If anything left to do here, please reopen
